service: rimac-starwar-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  timeout: 300
  environment: '${file(.env.yml):${self:custom.stage}}'
  stage: development

custom:
  webpack:
    webpackConfig: './webpack.config.${self:custom.stage}.js'
    includeModules:
      forceInclude:
        - sequelize
        - tedious
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    httpPort: 8082
    babelOptions:
      presets:
        - env

package:
  exclude:
    - .vscode/**
    - docs/**
    - templates/**
    - tests/**
    - .editorconfig
    - .env.yml.example
    - .eslintrc.js
    - .eslintrc
    - .jsbeautifyrc
    - .editorconfig
    - .git/**
    - .gitattributes
    - .gitignore
    - artifacts
    - .npmrc
    - jsdoc.conf
    - jsdoc.conf.json
    - README.md

functions:
  film:
    description: A Film resource is a single film.
    handler: functions/film.handler
    events:
      - http:
          path: api/film
          method: any
          cors: true

  people:
    description: A People resource is an individual person or character within the Star Wars universe.
    handler: functions/people.handler
    events:
      - http:
          path: api/people
          method: any
          cors: true

resources:
  Resources:
    ApiGatewayRestApi:
      Type: 'AWS::ApiGateway::RestApi'
      Properties: